jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: yarn build || true
      - run: yarn lint

name: Lint

on:
  pull_request: ~
  push:
    branches:
      - main
