jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: yarn format --list-different

name: Prettier

on:
  pull_request: ~
  push:
    branches:
      - main
